//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sconnRem.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sconnRem.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conf.
        /// </summary>
        public static string btnConfSiteDesc {
            get {
                return ResourceManager.GetString("btnConfSiteDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string btnLoginDesc {
            get {
                return ResourceManager.GetString("btnLoginDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSaveDesc {
            get {
                return ResourceManager.GetString("btnSaveDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string btnViewSiteDesc {
            get {
                return ResourceManager.GetString("btnViewSiteDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string lblActivateDesc {
            get {
                return ResourceManager.GetString("lblActivateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arm.
        /// </summary>
        public static string lblArmDesc {
            get {
                return ResourceManager.GetString("lblArmDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armed.
        /// </summary>
        public static string lblArmedDesc {
            get {
                return ResourceManager.GetString("lblArmedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armed or Disarmed Violation.
        /// </summary>
        public static string lblArmedOrDisarmedViolationDesc {
            get {
                return ResourceManager.GetString("lblArmedOrDisarmedViolationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armed Violation.
        /// </summary>
        public static string lblArmedViolationDesc {
            get {
                return ResourceManager.GetString("lblArmedViolationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arm State.
        /// </summary>
        public static string lblArmStateDesc {
            get {
                return ResourceManager.GetString("lblArmStateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average response time.
        /// </summary>
        public static string lblAvRespTimeDesc {
            get {
                return ResourceManager.GetString("lblAvRespTimeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string lblChangePasswordDesc {
            get {
                return ResourceManager.GetString("lblChangePasswordDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Password.
        /// </summary>
        public static string lblChangePasswordRepeatDesc {
            get {
                return ResourceManager.GetString("lblChangePasswordRepeatDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus adress.
        /// </summary>
        public static string lblcomBusAddrDesc {
            get {
                return ResourceManager.GetString("lblcomBusAddrDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus communication.
        /// </summary>
        public static string lblcomBusDesc {
            get {
                return ResourceManager.GetString("lblcomBusDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethernet communication.
        /// </summary>
        public static string lblcomETHDesc {
            get {
                return ResourceManager.GetString("lblcomETHDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireless communication.
        /// </summary>
        public static string lblcommiwiDesc {
            get {
                return ResourceManager.GetString("lblcommiwiDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        public static string lblConfigDesc {
            get {
                return ResourceManager.GetString("lblConfigDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect errors.
        /// </summary>
        public static string lblConnectErrorsDesc {
            get {
                return ResourceManager.GetString("lblConnectErrorsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string lblConnectionDesc {
            get {
                return ResourceManager.GetString("lblConnectionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection elapsed.
        /// </summary>
        public static string lblConnectionElapsedDesc {
            get {
                return ResourceManager.GetString("lblConnectionElapsedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        public static string lblDeactivateDesc {
            get {
                return ResourceManager.GetString("lblDeactivateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deamon Config.
        /// </summary>
        public static string lblDeamonDesc {
            get {
                return ResourceManager.GetString("lblDeamonDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Name.
        /// </summary>
        public static string lblDeviceNameDesc {
            get {
                return ResourceManager.GetString("lblDeviceNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Number.
        /// </summary>
        public static string lblDeviceNumberDesc {
            get {
                return ResourceManager.GetString("lblDeviceNumberDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Revision.
        /// </summary>
        public static string lblDeviceRevisionDesc {
            get {
                return ResourceManager.GetString("lblDeviceRevisionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string lblDevicesDesc {
            get {
                return ResourceManager.GetString("lblDevicesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Type.
        /// </summary>
        public static string lblDeviceTypeDesc {
            get {
                return ResourceManager.GetString("lblDeviceTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disarm.
        /// </summary>
        public static string lblDisarmDesc {
            get {
                return ResourceManager.GetString("lblDisarmDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disarmed.
        /// </summary>
        public static string lblDisarmedDesc {
            get {
                return ResourceManager.GetString("lblDisarmedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disarmed Violation.
        /// </summary>
        public static string lblDisarmedViolationDesc {
            get {
                return ResourceManager.GetString("lblDisarmedViolationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string lblDomainDesc {
            get {
                return ResourceManager.GetString("lblDomainDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        public static string lblFunctionDesc {
            get {
                return ResourceManager.GetString("lblFunctionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Config.
        /// </summary>
        public static string lblGlobalConfigDesc {
            get {
                return ResourceManager.GetString("lblGlobalConfigDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        public static string lblHumidityDesc {
            get {
                return ResourceManager.GetString("lblHumidityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input names.
        /// </summary>
        public static string lblInputNamesDes {
            get {
                return ResourceManager.GetString("lblInputNamesDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputs.
        /// </summary>
        public static string lblInputsDesc {
            get {
                return ResourceManager.GetString("lblInputsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keypad.
        /// </summary>
        public static string lblKeypadDesc {
            get {
                return ResourceManager.GetString("lblKeypadDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string lblOffDesc {
            get {
                return ResourceManager.GetString("lblOffDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string lblOnDesc {
            get {
                return ResourceManager.GetString("lblOnDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output names.
        /// </summary>
        public static string lblOutputNamesDesc {
            get {
                return ResourceManager.GetString("lblOutputNamesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outputs.
        /// </summary>
        public static string lblOutputsDesc {
            get {
                return ResourceManager.GetString("lblOutputsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lblPasswordDesc {
            get {
                return ResourceManager.GetString("lblPasswordDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        public static string lblPowerNamesDesc {
            get {
                return ResourceManager.GetString("lblPowerNamesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        public static string lblPressureDesc {
            get {
                return ResourceManager.GetString("lblPressureDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presure Module.
        /// </summary>
        public static string lblPresureDesc {
            get {
                return ResourceManager.GetString("lblPresureDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relay names.
        /// </summary>
        public static string lblRelayNamesDesc {
            get {
                return ResourceManager.GetString("lblRelayNamesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relays.
        /// </summary>
        public static string lblRelaysDesc {
            get {
                return ResourceManager.GetString("lblRelaysDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string lblScheduleDesc {
            get {
                return ResourceManager.GetString("lblScheduleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string lblSiteDesc {
            get {
                return ResourceManager.GetString("lblSiteDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticated.
        /// </summary>
        public static string lblStatus_Authenticated {
            get {
                return ResourceManager.GetString("lblStatus_Authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating.
        /// </summary>
        public static string lblStatus_Authenticating {
            get {
                return ResourceManager.GetString("lblStatus_Authenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string lblStatus_Connected {
            get {
                return ResourceManager.GetString("lblStatus_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect error.
        /// </summary>
        public static string lblStatus_ConnectError {
            get {
                return ResourceManager.GetString("lblStatus_ConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        public static string lblStatus_Connecting {
            get {
                return ResourceManager.GetString("lblStatus_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recieving.
        /// </summary>
        public static string lblStatus_Recieving {
            get {
                return ResourceManager.GetString("lblStatus_Recieving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting Data.
        /// </summary>
        public static string lblStatus_RequestingData {
            get {
                return ResourceManager.GetString("lblStatus_RequestingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string lblStatus_Success {
            get {
                return ResourceManager.GetString("lblStatus_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string lblSummaryDesc {
            get {
                return ResourceManager.GetString("lblSummaryDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string lblTemperatureDesc {
            get {
                return ResourceManager.GetString("lblTemperatureDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total inputs.
        /// </summary>
        public static string lblTotalInputsDesc {
            get {
                return ResourceManager.GetString("lblTotalInputsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outputs.
        /// </summary>
        public static string lblTotalOutputsDesc {
            get {
                return ResourceManager.GetString("lblTotalOutputsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string lblUsernameDesc {
            get {
                return ResourceManager.GetString("lblUsernameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violation.
        /// </summary>
        public static string lblViolationDesc {
            get {
                return ResourceManager.GetString("lblViolationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string mitemAboutHeader {
            get {
                return ResourceManager.GetString("mitemAboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string mitemFileHeader {
            get {
                return ResourceManager.GetString("mitemFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string mitemHelpHeader {
            get {
                return ResourceManager.GetString("mitemHelpHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string mitemLanguageHeader {
            get {
                return ResourceManager.GetString("mitemLanguageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string mitemSaveHeader {
            get {
                return ResourceManager.GetString("mitemSaveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string mitemSetupHeader {
            get {
                return ResourceManager.GetString("mitemSetupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string msubitemImportHeader {
            get {
                return ResourceManager.GetString("msubitemImportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string msubitemSaveAsHeader {
            get {
                return ResourceManager.GetString("msubitemSaveAsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string msubitemSaveHeader {
            get {
                return ResourceManager.GetString("msubitemSaveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string wndSecurityDialogTitle {
            get {
                return ResourceManager.GetString("wndSecurityDialogTitle", resourceCulture);
            }
        }
    }
}
