// <auto-generated />
namespace iotDatabaseConnector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class mapdeflatlng : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mapdeflatlng));
        
        string IMigrationMetadata.Id
        {
            get { return "201601141453304_map def lat lng "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
