// <auto-generated />
namespace iotDash.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class rc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rc));
        
        string IMigrationMetadata.Id
        {
            get { return "201502022159018_rc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
