// <auto-generated />
namespace iotDash.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Parameterchangehistory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Parameterchangehistory));
        
        string IMigrationMetadata.Id
        {
            get { return "201501231152434_Parameter change history"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
